# Generated by Django 6.0.1 on 2026-01-30 15:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source", models.CharField(max_length=50)),
                ("external_id", models.CharField(max_length=100)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("VALIDATED", "Validated"),
                            ("ENRICHED", "Enriched"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="tickets_tic_status_15eec8_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="tickets_tic_created_c2132d_idx"
                    ),
                ],
                "unique_together": {("source", "external_id")},
            },
        ),
    ]
